name: discri
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=1.21.3
  - ipython=7.28.0
  - tensorflow-estimator
  - obspy=1.2.2
  - matplotlib-base=3.4.3
  - pip : 
    - keras==2.8.0
    - keras-applications==1.0.8
    - tensorflow==2.8.0
    - tensorflow-io-gcs-filesystem==0.24.0
    - pip==22.0.3
